# Site settings
title: 1 tech 1 page - All About Front End
description: A blog about Front End
baseurl: "/1tech1page" # the subpath of your site, e.g. /blog
url: "http://github.Howie.Wang" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Howie Wang
user_description: Being DEVOPS
email: i@howie.wang
twitter_username: 
github_username:  howiewang
gplus_username:  
disqus_username: howie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
